### PR TITLE
gpd_xds: new port

### PR DESCRIPTION
**Pull request by oxr463**
Documentation: https://wiki.gentoo.org/wiki/User:Rage/Drafts/GPD_XD_PLUS_(mt8176)
Kernel Sources: https://gitlab.com/lramage94/android_kernel_mt8176_common/tree/sharkbait
Linux Headers: https://github.com/oxr463/android-overlay/tree/feature_mt8176/sys-kernel/linux-headers

### CODE REVIEW

**Review by KireinaHoro — CHANGES_REQUESTED** [review]
Does the device have a proper codename instead of `mt8176` (e.g. `hammerhead` or `angler`)?  The codename can be found in the `ro.product.device` Android property.  Use that for the port name instead.

**Comment by oxr463** [comment]
According to the `build.prop`,
```
ro.product.device=gpd_en
```

However, this is running [CleanROM 1.10.0.4](https://www.black-seraph.com/project/cleanrom-for-gpd-xd), by @Black-Seraph; an updated alternative to the stock rom, which contains `TWRP` recovery, and `Magisk`—this was the only way that I could even attempt porting the device. He is working on a `LineageOS` port for the device [here](https://github.com/Black-Seraph/android_device_gpd_xds), however it is still very much WIP; hence the more generic `mt8176`.

**Comment by KireinaHoro** [comment]
In that way, I suggest using something like `gpd_en-lineage` or the like
while explicitly stating that you're using an alternative OS in the
documentation.  The purpose of a board name is to specify the partition
layout and other information of the __device__ itself; another device with
the same SoC can have very different layouts.

2018年10月10日(水) 午前8:55 Rage <OxR463> <notifications@github.com>:

**Comment by Black-Seraph** [comment]
This device has no proper codename.

Even the original ROMs provided by GPD have varying codenames defined, and in general it seems like they use the codename to differentiate between regional ROMs, more than different device models.

What adds to the confusion is that there are two near-identical models on the market, that require two slightly different kernel configurations, which I've dubbed revision 1 and 2 for a lack of better naming schemes.

Codenames I've found so far... gpd, gpd_en, xdp, xds, with gpd_en seemingly being the gapp-equipped stock ROM for use outside of china, and gpd being the stock ROM for use inside of china.

This follows suit with the different firmware bundles GPD has been doing for their other devices, mostly their windows-equipped subvariants, where they dish out regional packages while completely ignoring potential hardware differences.

Their 1.11 firmware for example, rendered all revision 1 model audio jacks broken, as they seem to have dropped support for said revisions in favor of the revision 2 models, adding further confusion for regular endusers that might not grasp the technical differences between models, and only see the simple fact that their unit no longer works as intended.

As such, at least with GPD devices, it will be required to either go with a extremely generic device name, which GPD might just end up reusing in their future XD revisions, or make up a unique one ourselves and stick to that one for consistency from this point forward.

**Comment by KireinaHoro** [comment]
I see.  I'm for the latter approach, that is, to give a rather unique and
stable name ourselves; the SoC name seems to be way to general for this
case.

The documentation should list known possible board names for the device
though, so that we don't port a device multiple times.

2018年10月10日(水) 午後4:23 Black-Seraph <notifications@github.com>:

**Comment by oxr463** [comment]
@KireinaHoro, so how should I approach the kernel and the headers? Is this just for the android specific parts?

**Comment by KireinaHoro** [comment]
Yes.  Changes for ebuilds should go to the Android overlay.

@heroxbd could you please review this?  Also, what's the routine for pull
requests or the like with Gentoo overlays?

2018年10月11日(木) 午前0:34 Rage <OxR463> <notifications@github.com>:

**Comment by oxr463** [comment]
> Yes. Changes for ebuilds should go to the Android overlay.

I meant, should I rename anything for those? The kernel sources are for the SoC [1], not the device in particular [2]; same with the headers [3].

> Also, what's the routine for pull requests or the like with Gentoo overlays?

I was planning on just submitting a patch via email to @heroxbd, once my changes were reviewed.

[1]: https://gitlab.com/lramage94/android_kernel_mt8176_common/tree/sharkbait
[2]: https://gitlab.com/lramage94/android-overlay/commit/dbe1cd37e6ec0b05d176bd74a4da3b3369b6dbdf
[3]: https://gitlab.com/lramage94/android-overlay/commit/5e1afdd9712b27fe2a7eb0c5dcf67f362842595e

**Comment by KireinaHoro** [comment]
Those are okay.  Specify the relationship between the components clearly in
the documentation.

2018年10月11日(木) 午前1:06 Rage <OxR463> <notifications@github.com>:

**Comment by heroxbd** [comment]
LGTM.  For merging PR, let's follow the Gentoo general practice.

https://wiki.gentoo.org/wiki/Project:GitHub/Pull_requests

**Comment by oxr463** [comment]
> LGTM. For merging PR, let's follow the Gentoo general practice.
> 
> https://wiki.gentoo.org/wiki/Project:GitHub/Pull_requests

Just following up on this, is that something I need to do? Or do I just need to wait until it's merged?

**Comment by KireinaHoro** [comment]
Well, the Gentoo way seems to be a bit overkill for this...

@heroxbd I personally prefer directly merging on GitHub.  Or maybe you can
carry out the process (and I'll grant the relevant permissions on GitHub)?

2018年10月18日(木) 午前6:21 Rage <OxR463> <notifications@github.com>:

**Comment by oxr463** [comment]
@KireinaHoro , I can merge it here ([1]), if you'd like? It's been sitting for awhile..

[1]: https://github.com/SharkBaitOS/setup

**Comment by KireinaHoro** [comment]
Well there's nothing blocking I think, if it works on your device.  Do you have the merge permissions? 

Nvmd, I'll do it.  Thanks for the work!

**Pull request merged**
